import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "../components/Navbar";
import Providers from "@/components/Providers";
import { Toaster } from "sonner";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body
          className={cn(
            "font-sans min-h-screen antialiased grainy text-zinc-900",
            inter.className
          )}
        >
          <Toaster position="top-center" />
          <Navbar />
          {children}
        </body>
      </Providers>
    </html>
  );
}
